---
name: ghaction-cmake
on: push
jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir /usr/include/catch2
      - run: mkdir /usr/include/nlohmann
      - uses: wei/curl@v1.1.1
        with:
          args: https://github.com/catchorg/Catch2/releases/download/v2.11.1/catch.hpp /usr/include/catch2/catch.hpp
      - uses: wei/curl@v1.1.1
        with:
          args: https://github.com/nlohmann/json/releases/download/v3.7.3/json.hpp /usr/include/nlohmann/json.hpp        
  build:
    strategy:
      matrix:
        cc: [ gcc, clang ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lpenz/ghaction-cmake:latest
        with:
          cc: ${{ matrix.cc }}
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lpenz/ghaction-cmake:latest
        with:
          coverage: codecov
  valgrind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lpenz/ghaction-cmake:latest
        with:
          ctestflags: '-D ExperimentalMemCheck'
  clang-sanitizers:
    name: build with clang -fsanitize
    strategy:
      matrix:
        cflags:
          - -fsanitize=address
          - -fsanitize=memory
          - -fsanitize=undefined
          - -fsanitize=dataflow
          - -fsanitize=safe-stack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lpenz/ghaction-cmake:latest
        with:
          cc: clang
          cflags: ${{ matrix.cflags }}
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lpenz/ghaction-cmake:latest
        with:
          analyzer: clang-format
  clang-analyzers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lpenz/ghaction-cmake:latest
        with:
          analyzer: clang-tidy
